program     = decls

decls       = *(item item-sep) [item]
item        = fun-item / let-item / type-item
item       =/ eff-item / val-item

fun-item    = "fun" NAME "(" arg-list ")" item-def
let-item    = "let" NAME [":" add-expr] item-def
type-item   = "type" NAME maybe-def

eff-item    = "eff" NAME ["(" arg-list ")"] maybe-def
val-item    = "val" NAME ["(" arg-list ")"] ":" add-expr

item-def    = "=" expr
item-def   =/ stmts ["where" decls] "end" [opening-kw / opening-name]

maybe-def   = "=" expr
maybe-def  =/ ["is" stmts ["where" decls] "end" [opening-kw / opening-name]]


;
;   Statements
;

stmts       = *(stmt item-sep) [stmt]
stmt        = let-stmt / fun-stmt / expr-stmt
stmt       =/ case-stmt
stmt       =/ return-stmt

let-stmt    = ("let" / "var") NAME [":" add-expr] item-def
fun-stmt    = "fun" NAME "(" arg-list ")" item-def
expr-stmt   = expr

case-stmt   = "case" add-expr cases "end" ["case"]

return-stmt = "return" [expr] ["when" expr]

cases       = *(case item-sep) [case]
case        = cmp-ops add-expr case-body
case       =/ "else" case-body
case-body   = "=>" expr / stmts "end" [opening-kw]


;
;   Expressions
;

expr        = lam-expr

lam-expr    = "fun" "(" arg-list ")" "=>" lam-expr
lam-expr   =/ range-expr

range-expr  = anno-expr [("upto" / "thru") anno-expr]

anno-expr   = fun-expr [":" add-expr]

fun-expr    = log-expr ["->" fun-expr ["/" "{" *(NAME item-sep) [NAME] "}"]]
log-expr    = cmp-expr *(("and" ["then"] / "or" ["else"] / "xor") cmp-expr)
cmp-expr    = add-expr *(cmp-ops add-expr)
add-expr    = mul-expr *(("+" / "-") mul-expr)
mul-expr    = uni-expr *(("*" / "/" / "mod") uni-expr)
uni-expr    = ["-" / "not"] uni-expr / exp-expr
exp-expr    = num-expr ["**" exp-expr]

num-expr    = ("bits" / "digits" / "mod") add-expr
num-expr   =/ call-expr

call-expr   = base-expr *("(" arg-list ")")

base-expr   = NAME / NUMBER / REGEX / STRING
base-expr  =/ ("let" / "var") NAME
base-expr  =/ "(" *(expr item-sep) [expr] ")"


;
;   Separators and other utility rules
;

arg-list    = *(expr arg-sep) [expr]
arg-sep     = NEWLINE / ","
item-sep    = NEWLINE / ";"

cmp-ops     = "<" / "<=" / ">" / ">=" / "=" / "/=" / ["not"] "in" / "is"