//! Names uniquely identify certain items, and come in a few shapes.
//!
//! - **Contextual names** are most of the literal names in source code, whose
//!   full path is determined by context (such as scope and visible imports)
//! - **Fully qualified names** are names that contain the entire path from the
//!   relevant package root through all containing modules and items. These
//!   unambiguously refer either to one item or none.

pub use interner::{NameInterner, NameInternerStorage};

use salsa::{InternId, InternKey};

use crate::source::SourceId;

mod interner {
    #![allow(missing_docs)] // no docs for `lookup_*` methods

    use super::{Bare, BareData, Name, NameData};

    /// Responsible for mapping more heavyweight names (with their paths) to the
    /// lightweight [`Name`](super::Name) ids.
    #[salsa::query_group(NameInternerStorage)]
    pub trait NameInterner {
        /// Intern a fully qualified name to a lightweight id.
        #[salsa::interned]
        fn intern_name(&self, name: NameData) -> Name;

        /// Intern a field name to a lightweight id.
        #[salsa::interned]
        fn intern_bare(&self, field: BareData) -> Bare;
    }
}

/// A `Bare` in this context is a name without any of its lexical scoping
/// information (i.e. the bare name as it appears at its definition). The
/// [`NameInterner`] interns fields such that we won't have to carry `String`s
/// into the type checker or name resolver, and can instead determine field name
/// equality with a much more lightweight [`Bare`].
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub struct BareData(pub String);

/// A lightweight representation of a bare name.
#[derive(Clone, Copy, Debug, Hash, Eq, PartialEq)]
pub struct Bare(InternId);

impl InternKey for Bare {
    fn from_intern_id(v: InternId) -> Self {
        Self(v)
    }

    fn as_intern_id(&self) -> InternId {
        self.0
    }
}

/// A qualified name represents a complete, unambiguous path from the root
/// through pacakges and modules and other containing items with its final name
/// at the end.
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub enum NameData {
    /// A top-level item.
    Root(ActualName),

    /// Some name contained within another scope
    Child(Name, ActualName),
}

impl NameData {
    /// Get the name part of this name.
    pub fn get_actual(self) -> ActualName {
        match self {
            NameData::Root(name) => name,
            NameData::Child(_, name) => name,
        }
    }
}

/// The actual name as visible in the source, or a name generated by the
/// compiler.
#[derive(Clone, Debug, Hash, Eq, PartialEq)]
pub enum ActualName {
    /// A source-visible name.
    Name(String),

    /// The name of a file. Typically a root element.
    File(SourceId),

    /// A generated name.
    Generated(SourceId, usize),
}

/// `Name`s are lightweight types which unambiguously represent an item.
#[derive(Clone, Copy, Debug, Hash, Eq, PartialEq)]
pub struct Name(InternId);

impl InternKey for Name {
    fn from_intern_id(v: InternId) -> Self {
        Self(v)
    }

    fn as_intern_id(&self) -> InternId {
        self.0
    }
}
